name: audio2text
description: "Audio to text recording."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.0
  toastification: ^1.2.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  speech_to_text: ^6.6.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
